fasta: null
outdir: null
mat: True
dated: False
starting_tree: null
filter: 
  nextclade:
    - "Coverage >= 90"
tree: 
  threads: null
  batch_size_per_process: 10
  optimization_radius: 0
  include_reference: True
lineage:
  pango_collapse_url: https://raw.githubusercontent.com/MDU-PHL/pango-collapse/main/pango_collapse/collapse.txt
  threads: null
  unreleased: False

