SNAKEFILE = Path(workflow.main_snakefile).resolve()
WORKFLOW = SNAKEFILE.parent
RULES = WORKFLOW / "rules"
ENVS = WORKFLOW / "envs"
SCRIPTS = WORKFLOW / "scripts"
RESOURCES = WORKFLOW.parent / "data"

fasta_path = Path(config["fasta"]).resolve()
if config.get("name"):
    name = config["name"]
else:
    name = fasta_path.stem

if config.get("dated"):
    import datetime
    name = f"{datetime.datetime.now().strftime('%Y-%m-%dT%H%M%S.%f')}.{name}"

outdir = Path(config["outdir"]) if config.get("outdir") else Path.cwd()

rule all:
    input:
        tree=expand("{outdir}/{name}.nwk", name=name, outdir=outdir),
        metadata=expand("{outdir}/{name}.metadata.csv", name=name, outdir=outdir),
        report=expand("{outdir}/{name}.phytest-report.html", name=name, outdir=outdir)

include: RULES / "lineage.smk"
include: RULES / "filter.smk"
include: RULES / "tree.smk"
include: RULES / "phytest.smk"