SNAKEFILE = Path(workflow.main_snakefile).resolve()
WORKFLOW = SNAKEFILE.parent
RULES = WORKFLOW / "rules"
ENVS = WORKFLOW / "envs"
SCRIPTS = WORKFLOW / "scripts"
RESOURCES = WORKFLOW.parent / "data"

fasta_path = Path(config["fasta"]).resolve()
name = fasta_path.stem

if config.get("dated"):
    import datetime
    name = f"{datetime.datetime.now().strftime('%Y-%m-%dT%H%M%S.%f')}.{name}"

outdir = Path(config["outdir"]).resolve()

rule all:
    input:
        tree=expand("{outdir}/{name}.nwk", name=name, outdir=outdir),
        metadata=expand("{outdir}/{name}.metadata.tsv", name=name, outdir=outdir),

include: RULES / "lineage.smk"
include: RULES / "filter.smk"
include: RULES / "tree.smk"