from snk_cli import validate_config

SNAKEFILE = Path(workflow.main_snakefile).resolve()
WORKFLOW = SNAKEFILE.parent
RULES = WORKFLOW / "rules"
ENVS = WORKFLOW / "envs"
SCRIPTS = WORKFLOW / "scripts"
RESOURCES = WORKFLOW.parent / "data"

# Config 
validate_config(config, WORKFLOW.parent / "snk.yaml")

config["fasta"] = Path(config["fasta"]).resolve()
config["data"] = Path(config["data"]).resolve() if config.get("data") else None

name = config.get("name", config["fasta"].stem)

if config.get("dated"):
    import datetime
    name = f"{datetime.datetime.now().strftime('%Y-%m-%dT%H%M%S.%f')}.{name}"

outdir = Path(config["outdir"]) if config.get("outdir") else Path.cwd()
if config.get("data") and config["data"].name == f"{name}.metadata.csv":
    # snakemake weirdness
    raise ValueError(f"Data and cannot be named {name}.metadata.csv")

rule all:
    input:
        tree=f"{outdir}/{name}.nwk",
        metadata=f"{outdir}/{name}.metadata.csv",
        report=f"{outdir}/{name}.phytest-report.html"

include: RULES / "lineage.smk"
include: RULES / "filter.smk"
include: RULES / "tree.smk"
include: RULES / "phytest.smk"